// ─────────────────────────────────────────────────────────────
// Generate AI Images — example prompts
// Hand-curated prompts spanning portraits, landscapes, fantasy, sci-fi,
// animals, architecture, still life and abstract work.  Used by the dice
// button in the popup; the deck reshuffles only after every prompt has been
// shown once, so the user never sees the same example twice in a row.
// Concise but descriptive (~31 words): subject + key attributes + lighting/style,
// without the long trailing mood/extra-detail piles. Heavy surreal *composites*
// (a whale carrying a city, a person made of maps) are omitted entirely — the
// distilled SDXL-Lightning models can't hold those together and produce artifacts.
// ─────────────────────────────────────────────────────────────

export const PROMPTS = [
  // ── people / portraits ─────────────────────────────────────
  "Portrait of a young woman with long auburn hair holding a loose bouquet of ox-eye daisies, soft diffused morning light from the left, loose wet-on-wet watercolor washes",
  "An old fisherman mending nets at dawn on a weathered saltwater dock, gnarled calloused hands threading a wooden needle, heavy Aran wool sweater",
  "A small child blowing dandelion seeds in a sunlit summer meadow, seeds catching the backlight like tiny stars, bokeh blur of clover and cornflowers behind",
  "Full-body portrait of a steampunk inventor surrounded by intricate brass clockwork gears and whirring escapements, magnifying lens monocle, grease-stained leather apron over a ruffled shirt",
  "A lone samurai meditating in seiza beneath a dense canopy of falling cherry blossoms, petals settling on dark armor, ink wash painting style",
  "A jazz vocalist performing at a smoky 1940s Harlem nightclub, bias-cut sequined gown catching the amber spotlight, hand curling around a vintage ribbon microphone",
  "A ballerina captured at the apex of a grand-jeté on an empty stage, crisp white tutu frozen mid-flight, theatrical fresnels casting two overlapping spotlights",
  "An astronaut in a white EVA suit floating weightlessly above a sunlit blue Earth, the curved horizon visible in their gold-mirrored visor, a tether cable spiraling into the frame",
  "An elderly female librarian seated in a pool of golden afternoon light among floor-to-ceiling dusty bookshelves, bifocal reading glasses lowered on her nose, hand-knit cardigan",
  "A weathered pirate captain gripping the brass-fitted helm of a galleon in a raging ocean storm, torn brocade coat whipping horizontal, a jagged lightning bolt illuminating the entire rigging from behind",
  "Renaissance noblewoman in a deep crimson velvet gown with ermine-trimmed cuffs, baroque pearl choker, natural cool light entering from a high arched window at left",
  "A blacksmith hammering a glowing orange sword blade on an iron anvil, a constellation of orange and white sparks flying at oblique angles, forge firelight painting one side of a muscular tattooed arm in amber while the other falls to shadow",
  "A Tibetan Buddhist monk in saffron robes walking a narrow stone path through swirling cold mountain mist, amber prayer beads slipping through weathered fingers, towering snow-capped Himalayan peaks ghosting in and out of the cloud layer behind",
  "A cyberpunk hacker with neon-violet dyed undercut hair crouched in a rain-slicked Tokyo alley, holographic data streams reflecting off mirrored contact lenses, puddle-reflected neon kanji behind",
  "A meticulous bookbinder at a lamp-lit Victorian workbench, threading a curved needle through hand-stitched leather-covered signatures with practiced precision, a gold-tooling press and bone folder beside them",
  "A noir detective in a dripping belted trench coat and snap-brim fedora lighting a cigarette under a sputtering street lamp, rain-soaked granite pavement reflecting the flame, deep cinematic shadows reducing his face to a jaw and a glowing ember",
  "A beekeeper in a wide-brimmed veil hat holding a heavy honeycomb frame up to the light of a sun-drenched orchard, a dozen bees hovering mid-air around the frame, wildflower meadow soft in the background",
  "A mariachi guitarist in an elaborately embroidered charro suit serenading a couple beneath hand-painted paper lanterns at a twilight plaza festival, colorful papel picado bunting strung overhead, warm firelight kissing the cedar guitar top",
  "A surgeon in pale green scrubs and latex gloves bent over a delicate open procedure, a brilliant surgical theater lamp casting shadowless white light on the field, reflective instruments and clamps arranged with geometric precision",
  "A potter centering a large cylinder of dark terracotta clay on a fast-spinning wheel, both hands covered in wet slip, slurry spiraling upward",

  // ── animals ────────────────────────────────────────────────
  "A red fox curled into a tight ball in deep fresh powder snow, muzzle tucked beneath a bushy tail, fine frost crystals on its whiskers",
  "Twin Bengal tiger cubs tumbling and wrestling in long golden savanna grass, needle-sharp claws batting air, pink tongues lolling",
  "A great horned owl perched on a gnarled moss-covered oak branch in absolute stillness, amber-gold eyes wide and reflective, a large full moon emerging from ink-dark clouds directly behind",
  "A pod of seven bottlenose dolphins leaping in tight formation through a curtain of golden ocean spray at sunset, bodies arching in perfect synchrony, turquoise sea below",
  "An Indian peacock fully fanning its iridescent tail in a Mughal palace walled garden, each eye-spot a jewel of cobalt and emerald, jasmine hedges clipped low behind",
  "A large Pacific giant octopus hovering above a vivid Indo-Pacific coral reef, skin rippling through iridescent golds and teals as chromatophores fire, shafts of tropical sunlight penetrating crystal-clear water",
  "A lone grey wolf standing on a jagged basalt outcrop at cliff edge, head thrown back in a long howl, breath pluming white in the cold air",
  "A ruby-throated hummingbird suspended in dead-still mid-hover at a bright red trumpet hibiscus blossom, iridescent gorget catching green fire, wings a ghostly blur at 1/8000s",
  "A polar bear mother and young cub picking their way carefully across a cracked expanse of translucent blue Arctic sea ice, golden low-angle polar light painting their cream coats amber, meltwater pools reflecting the sky in turquoise mirrors",
  "A bright emerald iguana basking on a warm ochre adobe wall, textured spiny dorsal crest catching the afternoon sun, a single lidded eye sharp and appraising",
  "A barn owl gliding at roof-skimming altitude over a frost-silvered moonlit wheat field, bone-white wings spread to full two-foot span, primary feathers backlit by the moon",
  "A loggerhead sea turtle gliding majestically through shifting shafts of brilliant sunlight in clear turquoise water, twin remora fish riding the slipstream along a barnacled shell, soft caustic light patterns shimmering on white sand far below",
  "A matriarch African elephant leading three calves to a flaming-red sunset waterhole, trunks dipping to the copper surface, reflections shimmering in twin images below",
  "A cheetah at full explosive gallop across open Masai Mara plain, forepaws and hindpaws all off the ground simultaneously, a rooster-tail of dust and grass rising from powerful paws",
  "A scarlet macaw perched on a gnarled silvery piece of tropical driftwood, a towering jungle waterfall cascading fifty feet in the background, vivid scarlet-cobalt-yellow feathers tack-sharp against soft green bokeh",
  "A European hedgehog curled loosely into a half-ball among fallen chestnut and sycamore leaves, amber and umber tones warm with autumn, a delicate golden rim light separating each spine from shadow",
  "An adult male orca breaching explosively beside a tiny yellow sea kayak at pre-dawn, the full length of a six-ton body leaving the water, spray erupting in every direction",
  "A monarch butterfly mid-emergence from a jade-green and gold-dotted chrysalis, damp wings hanging like stained glass as they slowly unfold, venation mapping every orange-and-black panel",
  "A bald eagle in a near-vertical stoop, talons open and reaching for a leaping silver coho salmon above foaming white-water rapids, spray frozen in mid-explosion around both",
  "A black panther prowling with liquid grace through a vine-choked ancient Khmer stone temple courtyard at midnight, great amber eyes catching a shaft of moonlight between tangled roots, damp stone and deep shadows",

  // ── landscapes / nature ────────────────────────────────────
  "Dramatic Norwegian fjord at first light, rose-pink alpenglow mist clinging to a mirror-calm surface, a lone wooden rowing boat drifting in the middle distance",
  "Ancient Kyoto bamboo grove, dense jade-green columns rising thirty metres out of sight, a narrow moss-covered stone path winding through tightly packed culms",
  "Endless Provençal lavender field in full bloom stretching to a distant warm-stone farmhouse, low golden-hour sidelighting raking every row from the left, vivid violet and amber complementary palette",
  "Snow-capped Dolomite peaks perfectly reflected in the glassy surface of Lago di Braies at pre-dawn blue hour, a pale rose and mint sky overhead, black pine silhouettes mirrored in perfect symmetry below",
  "Dramatic Icelandic Reynisfjara black-sand beach, stacked hexagonal basalt columns rising twenty metres under a brooding overcast sky, vivid emerald moss coating the ledges",
  "Two camels crossing the knife-edge crest of a rust-orange Saharan dune at dusk, casting paired long blue-violet shadows across the warm amber sand face, a deep cobalt sky grading to dusty rose at the horizon",
  "Patagonian Torres del Paine granite spires piercing a wild storm ceiling, dramatic crepuscular god rays breaking through in amber shafts between the towers, vivid turquoise glacial lake below reflecting the turbulent sky",
  "Secret tropical lagoon, a hidden waterfall cascading fifteen metres into crystal-clear cyan water, dense canopy of giant tree ferns and heliconias overhanging the pool",
  "Vermont maple forest at peak autumn blaze, crimson, scarlet and molten-gold canopy framing a narrow lichen-covered stone bridge over a rushing brook",
  "Cherry blossom tunnel arching over a narrow Kyoto canal, pale pink petals floating densely on the slow dark water below, soft diffused overcast spring light with no hard shadows",
  "Tuscan rolling wheat fields at harvest sunset, a single gnarled ancient olive tree casting a long blue shadow east across golden stubble, warm amber raking sidelight from the left",
  "Dozens of vibrantly patterned hot-air balloons rising in a soft purple pre-dawn over the eroded fairy-chimney pinnacles of Cappadocia, basket propane flames glowing orange, long shadows raking the tufa formations below",
  "Sweeping aurora borealis in full dancing curtains of vivid emerald and deep violet above a snow-laden Finnish Lapland boreal pine forest, Milky Way core blazing cold through the gaps, long-exposure photography look with faint light trails in the snowfield",
  "Classic rolling Tuscan landscape in early morning, a winding cypress-lined dirt road cutting diagonally toward a stone farmhouse, soft pearlescent mist pooling in the lower valley",
  "Vast Bolivian Salar de Uyuni salt flat at moonless midnight, cracked hexagonal crust an absolute mirror reflecting the dense Milky Way core and the Magellanic Clouds, a tiny human silhouette at dead centre holding a single red torch",
  "Vivid acid-turquoise volcanic crater lake of Kelimutu on Flores, viewed from the knife-edge rim, sulfurous steam venting from one shore",
  "Bali Jatiluwih rice terraces glowing jade and amber gold in the first raking light of sunrise, thin mist curling between the contour tiers, a lone farmer in a woven palm-leaf hat walking a narrow dike",
  "Ancient coastal California redwood grove at noon, trunks twelve feet across disappearing into fog overhead, cathedral shafts of warm amber light angling through the mist and illuminating floating spore columns",
  "Bridalveil Falls frozen mid-cascade in February, massive pale ice-blue columns and frozen curtains suspended from the lip, frosted black pines clustered at the base",
  "Infinite Oklahoma sunflower field at peak bloom, every disc-flower tracking south under a deep cobalt sky piled with towering cumulus anvils, a lone weathered red tractor at the vanishing point",

  // ── architecture / cityscapes ──────────────────────────────
  "Tokyo Shibuya scramble crossing at 2 a.m. in heavy rain, neon advertisements in kanji and English blazing down from every building face, reflections fracturing in the standing water on black asphalt",
  "Marrakesh souk alley at golden hour, rows of hand-hammered brass lanterns hanging low and glowing amber, tightly stacked bolts of vivid hand-woven carpet in saffron",
  "Brooklyn rooftop bar at magic hour, two weathered water towers silhouetted against a deep amber and rose sky, the full Midtown Manhattan skyline glowing in warm golden light behind",
  "Lisbon Alfama hillside with a vintage canary-yellow tram climbing a steep hand-laid mosaic-paved street, intricate azulejo tile facades in Delft blue and white flanking both sides, the silver Tagus river glinting far below",
  "A classic Paris brasserie terrace in a warm autumn rain, straw bistro chairs glistening under a zinc awning, golden window glow spilling onto the wet pavement outside",
  "Old Havana calle at high noon, a 1957 Chevrolet Bel Air in two-tone turquoise and ivory parked before peeling pastel facades in coral, ochre and sky blue",
  "Seoul Gwangjang traditional market at night, a dense grid of pojangmacha street-food stalls under warm string lights and red awnings, thick steam rising from bindaetteok mung-bean griddles",
  "Cycladic Santorini village stepped white-cube architecture cascading down a volcanic caldera cliff to a vivid Aegean turquoise below, a single blue-domed Orthodox church perfectly centred, cascades of magenta bougainvillea against whitewash",
  "Jodhpur blue city panorama from the upper ramparts of Mehrangarh Fort at blue hour, an endless sea of indigo and cobalt-painted rooftops stretching to a dusty horizon, warm amber lamp windows beginning to glow",
  "Venice dense winter morning fog on a narrow rio canal, a black gondola gliding silently under a moss-streaked stone bridge, nobody visible in any direction",
  "Powell's City of Books Portland interior, a soaring spiral iron staircase rising to the upper gallery mezzanine, floor-to-ceiling shelves of second-hand spines in every colour",
  "Loire Valley Château de Chambord at golden hour, the elaborate French Renaissance roofline of towers and dormers perfectly reflected in a still ornamental moat, row of clipped linden topiaries along the gravel allée",
  "Paul Rudolph-style brutalist library exterior in a soft afternoon rain, deeply channelled corduroy board-formed concrete texture, a single Yoshino cherry in full white blossom in the courtyard catching the grey diffused light",
  "Norwegian Lofoten archipelago fishing village in deep winter, candy-colored rorbu fishermen's cabins on stilts mirrored in glassy jet-black fjord water, sheer snow-dusted Lofoten peaks behind",
  "Amalfi coast serpentine cliff road at golden hour, lemon and bergamot groves terraced impossibly steep above, tiny pastel-painted villages of Positano and Praiano spilling down to the deep Mediterranean far below",
  "Edinburgh Royal Mile Old Town closes in a thunderstorm, sixteenth-century tenement cobblestones slick and mirroring Victorian cast-iron gas lamps, deep puddles reflecting the gothic spires and black chimney pots above",
  "Bagan Myanmar plains at dawn, over two thousand ancient Pagan pagodas and temples rising from a flat dry-season morning mist in every direction, orange-robed monks cycling narrow dirt paths between the spires",
  "Edo-period Japanese ryokan inn half-buried in waist-deep fresh snowfall, warm orange glow seeping through rice-paper shoji screens into the blue darkness outside, a bamboo gate and a granite yukimi stone lantern in the foreground casting a small pool of amber",
  "Glass-and-steel International Style modernist house cantilevered dramatically over a deep Pacific Northwest forest ravine, warm interior amber lights glowing through full-height floor-to-ceiling glazing, old-growth Douglas fir mist rising from the gorge below",
  "Roman Baths at Bath filled with steaming sage-green geothermal water, classical Corinthian stone columns and Georgian viewing gallery above, a slant of warm late-afternoon golden light striking the water at a low angle",

  // ── sci-fi / futuristic ────────────────────────────────────
  "Solar-punk arcology city rising above a reclaimed estuary, towers clad in vertical gardens of ferns and food crops, tensioned solar canopy sails casting warm dappled shade on canal streets below",
  "A deep-space colony ship the size of a city breaching the upper atmosphere of a blue-green Earth-like planet, twin plasma contrails glowing white and burnt orange against the cloud deck, sharp high-altitude sunlight raking one side of the hull",
  "An astronaut in a sun-bleached worn EVA suit walking through waist-high amber alien grass swaying in a warm low wind, two orange dwarf suns setting side by side painting the sky copper and rose, no landmarks in any direction",
  "A cyberpunk female samurai on a rain-slicked Neo-Tokyo rooftop, katana resting on her shoulder, towering neon kanji advertisements reflected in puddles at her feet",
  "A deep-sea research station warmly lit from within, its domed observation window pressed against abyssal darkness, bioluminescent siphonophores and comb jellies drifting past in cold currents outside",
  "A Mars colony settlement at sunset under a butterscotch sky, white geodesic dome habitats and tilted solar arrays casting long blue shadows over rust-red regolith, a dust devil spiralling on the far horizon",
  "Two scientists in microgravity playing holographic chess in a ring-shaped space station module, blue holographic pieces floating between them, Earth turning slowly in a wide porthole",
  "A cryo-generation ship corridor abandoned for decades, overtaken by phosphorescent vines and bioluminescent fungi, emergency lights casting pools of amber and acid green along the curved bulkhead",
  "A battered service robot in faded coveralls tending a thriving hydroponic greenhouse inside an abandoned lunar base, sunlight pouring through a cracked skylight onto rows of tomatoes and herbs, warm greens and yellow-white light contrasting the cold grey regolith visible through the porthole window",
  "A Blade Runner-style spinner flying car banking steeply on descent into a mile-high neon mega-city canyon in heavy acid rain, headlights stabbing through volumetric fog, grates venting steam far below",
  "Cracked icy surface of Europa glowing pale blue at sunrise, Jupiter filling nearly half the sky in bands of cream, tan and storm-brown",
  "An asteroid mining rig clamped to a slowly rotating nickel-iron rock the size of a city block, arc welding sparks drifting away in vacuum like orange snow, the Milky Way densely banded behind",
  "An interstellar relay station orbiting a searing blue-white binary star system, paired solar sail arrays deployed wide, a coherent communication laser beam scattering through the tenuous upper atmosphere of the nearer star",
  "A cryogenic AI core room deep underground, liquid-nitrogen-cooled server stacks extending floor to ceiling in cathedral rows, blue-violet light caustic through cooling fluid channels",
  "A lunar radio-telescope observatory at local midnight, a massive parabolic dish silhouetted sharp against a full-resolution star field, Earth rising low and blue over the crater rim behind",
  "Floating modular city-platforms of glass and reclaimed steel tethered by sky-bridges above a flooded coastal megacity, rooftop gardens and billowing solar sails overhead, the upper floors of drowned skyscrapers visible below the waterline",
  "A female combat pilot inside a sleek articulated mech cockpit, jaw set, looking through reinforced polycarbonate glass at a war-torn alien cityscape of shattered spires and drifting smoke",
  "An abandoned spaceport reclaimed by a gene-engineered jungle, hexagonal landing pads cracked apart by massive root systems, vines spiralling up decommissioned fuel towers",
  "A black hole event horizon photographed from a shielded probe at minimum safe range, gravitational lensing warping the dense star field into a perfect Einstein ring, the thin accretion disk blazing in gradients of orange",
  "Crystalline alien forest of translucent teal and deep violet mineral spires rising forty metres from a pale stone plain, chitinous insectoid creatures skittering along their faceted surfaces, a diffuse pale alien sun refracting prismatic rainbow arcs through every crystal",

  // ── fantasy / mythology ────────────────────────────────────
  "A colossal silver dragon coiled protectively atop a moonlit ruined citadel, each overlapping scale catching cool moonlight like hammered metal, bats spiralling in chaotic clouds around the broken towers",
  "An elven archer in ancient tarnished silver armour standing in a forest glade where every moss-covered oak trunk glows with softly pulsing golden runes, deep violet twilight sky visible through the high canopy, long white hair loose in the still air",
  "An ancient wizard's tower interior lit only by a slowly orbiting constellation of glowing runes and hundreds of dripping tallow candles, leather-bound bookshelves fading into upper shadow, an open grimoire on a stone pedestal with hand-drawn illustrations",
  "A mermaid resting on storm-swept coastal rocks in a lightning-lit seascape, long dark wet hair plastered over her shoulders, iridescent green-gold scaled tail trailing into the foam",
  "A young witch in a beam-ceilinged herb-strewn cottage stirring a bubbling cauldron, bundles of drying lavender, wormwood and nightshade hanging from dark oak beams",
  "A phoenix erupting skyward from a pyre of white and gold embers, enormous feathers of living flame spread wide like a crown, a column of rising embers and gold sparks ascending around it against a deep charcoal background",
  "A lone knight in dented scarred plate armour crossing a desolate heather moorland at first grey light, the tattered silk banner of a long-forgotten order snapping in a cold easterly wind, dense fog pooling in the valley below hiding any road forward",
  "A centaur scholar seated at ease beneath a vast ancient twisted yew tree, carefully unrolling a vellum scroll across his equine flank, a bulging leather satchel of codices beside him",
  "An ancient underwater kingdom of soaring coral spires in pink and ochre, luminescent jellyfish lanterns drifting between the towers, mermaid palace architecture carved from bone-white stone with flowing organic ornament",
  "A snow-laden Shinto mountain shrine deep in a winter forest, guarded by a pair of moss-dusted stone kitsune foxes whose eyes glow warm amber in the darkness, bare cherry tree branches loaded with fresh snow",
  "A soaring crystal cavern where a white unicorn sleeps on a bed of luminous emerald moss, floor-to-ceiling quartz formations reflecting its soft inner glow in cascading prismatic patterns on the cave walls, absolute tranquility and sacred silence",
  "A weather-beaten ancient druid with a great branching antler staff raising massive granite pillars from the earth at dusk, the stones trailing soil and root systems as they rise, green vines spiralling up their rough surfaces",
  "A vast dwarven mead hall carved from living basalt, rivers of slow orange lava running in iron-edged troughs below chain-hung bridges, great feasting tables loaded with roasted boar and foaming ale",
  "The Great Sphinx addressing a lone cloaked traveler under a total solar eclipse, the diamond-ring corona blazing around the black disc above, fine sand swirling in sudden shadow across the Giza plateau",
  "A chain of floating jungle islands tethered together by enormous bioluminescent root bridges, waterfalls of tropical water spilling off their edges and vanishing into clouds far below, dense canopy of ferns and palms covering every surface",
  "A towering ancient forest spirit, its immense body woven from living moss, twisted root and dark branching antlers",
  "A goblin night market deep inside a stalactite-hung cave system, crowded stalls selling bottled starlight in cork-sealed vials, stolen dreams in stoppered mason jars",
  "A Norse sea serpent the size of a humpback whale coiling its vast body around a Viking longship at midnight, a bolt of lightning frozen mid-strike illuminating every writhing scale in white light, terrified crew clinging to the gunwales",
  "A nine-tailed kitsune in a flowing white silk kimono dancing on the curved roof tiles of a moonlit Heian-era temple, each of her nine tails a luminous streamer of blue-white foxfire curling in the still air, cherry blossom petals drifting down through the cold moonlight around her",
  "A wizard duel in a ruined Romanesque great hall, two robed figures hurling arcs of silver and crackling black lightning toward each other, the flagstone floor shattering in concentric rings of force",

  // ── still life / food ──────────────────────────────────────
  "Rustic farmhouse table spread with torn sourdough revealing an open crumb, aged comté with a wedge cut free, walnuts",
  "A wide shallow bowl of pomegranate arils glistening like wet rubies, a bronze-handled paring knife resting across the rim, a torn peel curled beside",
  "Steam spiraling from the spout of a hand-thrown iron-glazed stoneware teapot on a worn oak windowsill, soft early morning backlight rimming the form in gold, a single faded ranunculus in a small green bottle beside it",
  "Towering stack of six blueberry buttermilk pancakes crowned with a slowly melting pat of Normandy butter releasing golden rivulets of dark maple syrup over the sides, powdered sugar drifting, fresh summer blueberries scattered around the plate",
  "A deep lacquered bowl of Hakata tonkotsu ramen, opaque pork-bone broth, two braised chashu slices",
  "An elaborate charcuterie board: paper-thin jamón ibérico in loose folds, a ripe Époisses with rind split, dark honeycomb dripping",
  "Rows of Ladurée-style macarons in rose, pale pistachio, lavender",
  "A sliced watermelon on a red-and-white checkered cloth on a weathered porch table, dripping ruby-red flesh catching harsh noon sun, glistening black seeds",
  "An apothecary still life: antique brass balance scales weighing coriander seeds against dried rose petals, amber glass vials sealed with wax stoppers, brown paper packets tied with twine",
  "A hand-thrown ceramic coffee cup still steaming, three well-worn leather books with cracked spines, a bone-handled pocket knife and a sprig of rosemary laid on rough undyed linen cloth",
  "A single just-opened Pacific oyster on a deep bed of crushed ice, the plump silver flesh still trembling, a wedge of lemon bleeding pale juice across the pearlescent shell",
  "A rustic French galette des rois cooling on a wire rack above a flour-dusted marble slab, golden puff pastry with a burnished egg-wash crown in a sunray pattern, flaky laminated layers visible at the cut edge",
  "A silver Baroque compote overflowing with dusky concord grapes and ripe figs, several fallen to a cold stone ledge, a half-peeled lemon with a spiraling rind",
  "A vintage Olivetti Lettera 32 typewriter with a half-typed cream letter still in the carriage, a glass inkwell with a resting fountain pen, an afternoon patch of dusty window light falling across the keys",
  "A lazy Sunday dim sum spread, bamboo steamers stacked three high on a round family table, translucent pleated har gow",
  "A heavy Weck glass jar of raw amber honey with a dark comb dripping slowly from the hinged lid, warm golden rivulets threading down the sides, a scatter of dried lavender and a honey dipper on the stone counter",
  "A celebration birthday cake on a dark table with five lit silver sparklers fizzing and throwing bright stars, one generous slice removed to reveal alternating lemon sponge and raspberry cream layers, the warm faces of gathered family barely lit at the frame edges",
  "A navigator's chart table strewn with a partially unrolled admiralty chart, an aged leather-bound globe worn at the poles, a polished brass sextant at 45 degrees",
  "A perfect single croissant still warm from the oven, its flaky laminated layers tearing open to show the honeycomb interior, resting beside a small white porcelain demitasse of short espresso on a grey Carrara marble cafe table",
  "Eleven-piece sushi omakase arranged on a long charcoal-black slate, each nigiri glistening with a fine brushing of soy, a small quenelle of vivid green wasabi and a fan of pickled ginger at the far end",

  // ── abstract / artistic ───────────────────────────────────
  "Liquid chrome and mercury swirling and merging into perfect fractal flower geometries, hyperreal macro photography on absolute black, each curved surface holding a tiny distorted world in reflection",
  "An impossible Escher-inspired infinite staircase built in soft pastel blues and dusty rose pinks, dozens of small figures simultaneously ascending from every direction at once, the perspective mathematically perfect and spatially impossible",
  "A stained-glass window composed entirely of pressed autumn leaves, jewel-toned beetle elytra, and dried flower petals arranged in a rose-window geometric pattern",
  "A colour-field study of a Pacific sunset compressed into thirty-two precise horizontal bands grading from deep prussian navy at the top through slate violet, dusty rose, warm peach",
  "Black India ink dropped from height into a tall column of still clear water, frozen at the exact peak of explosion into radial fractal plumes of branching tendrils and ink clouds, backlit against clean white",
  "An origami paper crane caught in the exact moment of mid-transformation, its near-complete wings beginning to unfold and dissolve into a flock of forty smaller ascending cranes that disperse into the clean white negative space above, clean minimalist Japanese illustration on thick washi",
  "Synesthesia study: the sound of a Coleman Hawkins tenor saxophone solo rendered as interlocking ribbons of warm raw ochre, cinnabar and cadmium gold spiraling dynamically through a deep cool teal-black space, abstract digital painting with visible brushwork",
  "Classical Carrara marble sculpture of two outstretched hands reaching toward each other and stopping just short of contact, sharp single-source Caravaggio-style sidelighting cutting hard shadows, high-contrast monochrome photography on black velvet",
  "A Malevich Suprematist composition reinterpreted using living ocean materials: a red square of flat branching coral, a black circle of closely packed sea urchins, a diagonal of silver sardines",
  "A Bauhaus movement portrait of a violinist fully reduced to bold flat geometry: circles and rectangles of pure cadmium red, chrome yellow, jet black and warm grey",
  "A Dalí-esque desert plateau under a cloudless cobalt sky with melting gold pocket watches draped over bleached cattle bones and door frames that open onto more desert, a distant lithic spire casting an impossible shadow, hyper-real surrealist oil painting",
  "An illuminated manuscript page with interlocking triple-strand Celtic knotwork border in lapis and vermilion, a fire-breathing wyvern coiling through the ornate lower marginalia, penwork acanthus scrolls",
  "A Risograph print of an astronaut cat wearing a fishbowl helmet floating weightless in deep space, vivid duotone of fluorescent orange and cobalt blue over a cream ground, halftone dot pattern visible at medium resolution",
  "A Cubist still life of a ceramic bowl of pears seen simultaneously from six perspectives: above, below, left",
  "An Op-art vortex tunnel of alternating black and white concentric rings that pulls the eye irresistibly into the centre through hypnotic forced perspective, perfect bilateral symmetry, a visible moiré shimmer effect across the printed surface",
  "Takashi Murakami super-flat style flower-clouds in neon pink and chrome yellow floating above a miniaturized hyper-detailed Shibuya scramble crossing at night, LED billboards, anime sky with perfectly round moon",
  "A single bold Chinese ink dragon coiling with perfect calligraphic control around a large solitary kanji character for 'strength', bold wet-dry brushwork contrast from thick saturated ink to hairline dry-brush, white paper negative space used decisively",
  "A mandala constructed from the exploded components of a Swiss pocket watch — lever escapements, balance wheels, jewel pallets",
  "A Roy Lichtenstein-style pop art panel of a fashion model with a speech bubble reading 'Is that ALL he said?', bold primary Ben-Day halftone dots on flat areas, thick even black outlines",
  "A Soviet Constructivist propaganda poster announcing the year 2089, bold red and black diagonal composition, photomontage of orbital space technology",

  // ── atmospheric / weather / time of day ───────────────────
  "A single-lane country road dissolving into dense grey ground fog at dusk, one warm amber farmhouse window the only point of light, bare skeletal oaks lining both shoulders",
  "A dramatic supercell lightning storm over a Kansas wheat field at blue hour, five simultaneous ground strikes illuminating the cloud base in brilliant white-violet, a combine silhouetted at the field edge",
  "Summer afternoon rain on an old screen porch in rural Georgia, a cane rocking chair motionless, fat drops running in silver rivulets down the rusted mesh",
  "First snowfall of winter on an empty elementary school playground at pre-dawn, swings motionless on their chains, the slide dusted in unbroken white",
  "Heat shimmer rising in visible waves off black asphalt on a Route 66 desert highway stretching to a perfect vanishing point at midday, two Joshua trees framing the left foreground, a flat-topped mesa dissolving in the shimmer on the horizon",
  "Pre-dawn mist filling the bowl of a Scottish glen at first cold light, heather-covered rolling hills barely visible as cool violet-grey forms, three sheep standing as dark silhouettes in the middle ground",
  "Large hailstones the size of marbles pelting a Victorian cast-iron-and-glass conservatory in a summer squall, tropical ferns and banana palms pressed against the interior panes, steam condensation fogging the glass",
  "Northern lights in broad sweeping curtains of vivid acid-green and deep fuchsia above a frozen Icelandic river delta, fractured ice pressure ridges holding the reflected colour like stained glass, a perfectly clear starfield overhead",
  "Prairie sunset behind a rusted water tower hand-painted with a fading Hereford cattle scene above a ghost town, magenta-orange sky grading to deep cobalt overhead, three power lines in hard silhouette",
  "Moonlit beach at king tide, a dense bloom of bioluminescent dinoflagellates lighting each breaking wave crest in electric cobalt blue, a lone dark figure standing at the waterline",
  "A dust devil lifting bright red sandstone soil in a tight twisting column across a ghost-town Arizona main street at three in the afternoon, old hand-painted signage flapping on a single rusted hinge, the surrounding landscape dead still under a bleached flat sky",
  "Late afternoon supercell thunderclouds building into a classic anvil above the Midtown Manhattan skyline, Empire State Building needle in crisp silhouette, warm amber pre-storm light flooding the street canyons below the dark cloud base",
  "A walled Andalusian garden at absolute solar noon, dense black shadows pooled beneath ancient olive trees like spilled ink, white-hot limestone stonework almost too bright to look at",
  "Frost-fern crystals covering an entire bay window in deep mid-January winter, a single white taper candle burning on the inner sill casting a warm amber corona across the ice, blue-black darkness and undisturbed snow outside",
  "Pre-dawn New England harbour at 4:30 a.m., three lobster boats motoring out through still black water on a windless morning, green and red running lights reflecting in long wavering neon streaks below",
  "Mumbai monsoon flooding a busy market street to ankle depth, yellow taxis forging slow bow-waves with headlights on in the grey rain, pedestrians under umbrellas and plastic-bag hats",
  "A tornado funnel fully extended to the ground on the far horizon of a flat Iowa corn farm, twisting dark column in a sickly green-yellow overcast sky, the farm's white silo and red barn sitting quiet in the foreground",
  "Twilight rain beginning on a deserted Venetian campo, gas lanterns flickering on in warm windows around the square, raindrops fracturing reflections on wet terracotta marble",
  "Total solar eclipse darkness falling on a crowded city park in ninety seconds, premature sodium-lamp glow switching on along the paths, confused pigeons wheeling and landing",
  "A single broad shaft of late afternoon sun breaking between two enormous old beech trees after a rain, illuminating a slow-drifting cloud of golden pollen grains and tiny water droplets suspended in the beam, the rest of the scene in cool blue-green shadow",

  // ── vehicles / machines ────────────────────────────────────
  "A perfectly restored 1965 Ford Mustang fastback in Wimbledon White on a sweeping Pacific Coast Highway curve at sunset, chrome front bumper catching the last direct sunlight, the car's long shadow stretching east across bleached asphalt",
  "A vintage steam locomotive at full throttle crossing a curved wooden trestle bridge above a deep forested gorge, a billowing plume of white steam trailing two hundred feet behind, the drive wheels a motion-blurred spiral",
  "A classic mahogany racing yacht heeled hard to starboard in a Force 5 westerly, the windward rail buried in white bow wave hissing past teak decks, four crew members hiking out over the side in lifejackets",
  "A cherry red vintage Vespa 150 Super parked on damp cobblestones outside a Roman bar, an espresso cup steaming on the marble sill in the window above, old hand-painted typography on the facade",
  "An F-22 Raptor punching through Mach 1 at low altitude over the Pacific, the perfect Prandtl-Glauert condensation cone forming as a white vapour disc around the fuselage, twin afterburner plumes burning deep amber behind",
  "A silver Graf Zeppelin-era rigid airship mooring above a 1920s art deco passenger terminal, long hemp mooring ropes held by sixty ground crew in period uniforms, a biplane escort banking away to port",
  "A cyberpunk custom cafe racer with electric blue neon underglow racing flat-out through a rain-drenched LED-strip tunnel at midnight, background smeared to light streaks by motion blur, rider's helmet sharp in the frame",
  "A 1957 Chevrolet Bel Air in two-tone turquoise and white parked under a buzzing neon drive-in diner sign at blue dusk, a carhop on roller skates approaching with a tray of frosted root beers, the chrome bumper and tail fins lit by warm amber neon",
  "A hand-built 1930s Vincent Black Shadow motorcycle resting on a centre stand in a dusty sunlit timber barn, a single angled shaft of afternoon light picking out the polished primary case and the engine's finned barrels, old rusted tools hanging on pegboard behind",
  "A solar-panelled two-seat glider banking gently above a jagged Andean ridge at 18,000 feet, long thin wings glittering with photovoltaic cells, an Andean condor soaring the same ridge thermal fifty feet away",

  // ── seasonal / festive ─────────────────────────────────────
  "A German Christmas market in a cobblestoned square during fresh evening snowfall, mulled wine stall with a column of fragrant steam rising, golden string lights draped on snow-laden fir trees",
  "A creaking New England farmhouse at Halloween dusk, a row of elaborately carved jack-o-lanterns lining the porch steps with flickering candles inside, warm orange glow in every frost-paned window",
  "Diwali night on a Jaipur rooftop terrace, hundreds of hand-thrown terracotta diyas arranged in spiraling rows casting warm orange light across white marble, sparklers tracing golden arcs",
  "Easter brunch in a sunlit country kitchen, a woven basket of blue and yellow hand-painted eggs on a linen tablecloth, fat tulips in a painted jug",
  "New Year's Eve fireworks lighting up Sydney Harbour Bridge at midnight, the illuminated sails of the Opera House in the foreground, massive chrysanthemum bursts of gold and silver reflecting in shimmering trails on the harbour",
  "Pingxi Sky Lantern Festival on the dark Jilong River at night, hundreds of glowing red and amber paper lanterns ascending in a dense towering column, warm orange luminance against a deep blue-black sky",
  "A Day of the Dead home altar built on tiered steps and overflowing with vivid marigold cempasúchil petals, framed sepia photographs of ancestors, elaborately painted sugar skulls",
  "Hanami flower-viewing picnic beneath a Somei Yoshino cherry tree at peak bloom, spread of lacquered bento boxes, sakura mochi wrapped in pale pink leaves",
  "A Bavarian Oktoberfest giant beer tent at peak evening revelry, long rows of pine tables packed with steins raised high in a collective toast, a dirndl-clad waitress carrying six one-litre Maß",
  "Midsommar celebration on a Swedish archipelago beach at the midnight sun, the sky a pale golden light that never darkens, barefoot dancers in folk costumes weaving around a flower-garlanded maypole",

  // ── people in context (slice-of-life) ─────────────────────
  "Two best friends mid-laughter on a bleached driftwood log at a rocky Pacific beach at golden hour, one throwing her head back with eyes closed, warm backlight haloing their hair and catching tears of laughter",
  "A family of four lying on wool blankets in the bed of a dusty old pickup truck, faces turned up to a blazing Wyoming dark-sky Milky Way, a red-glowing thermos of cocoa between the parents",
  "A Polish babcia in a floral apron teaching her granddaughter to seal a pierogi at a flour-dusted wooden kitchen table, the child's brow furrowed in fierce concentration, a bowl of potato-and-cheese filling beside them",
  "A young couple on a near-empty late-night Tokyo subway car sharing one set of earphones, heads tilting together, faces close and slightly smiling with eyes half-closed",
  "A teenage skateboarder at the apex of a kickflip over an empty downtown concrete fountain, the board frozen horizontal beneath their feet, warm golden late afternoon sidelighting casting long shadows",
  "A woman in a pale linen dress writing a postcard at a marble-topped sidewalk cafe table in Rome, a sweating glass of Campari beside her hand, a straw hat hooked on the chair back",
  "A father reading a well-worn paperback bedtime story to a wide-eyed toddler tucked under a patchwork quilt, the child's chin resting on their dad's forearm, a small bedside lamp casting warm amber light on both faces",
  "Two rock climbers on a sun-warmed vertical granite face in Yosemite, one belaying from a ledge stance while the other makes a delicate crimping move twelve feet above, chalk marks on the pale stone",
  "A street quartet sheltering under a moss-covered stone bridge arch in a Paris rain — cello, violin, viola and double bass — eyes closed and playing with full feeling",
  "An early morning yoga class on a dew-slick cedar deck in a misty Pacific Northwest second-growth forest, five participants in warrior II pose, thin shafts of rose-gold dawn light slanting through tall Douglas firs",

  // ── moods / colour studies ────────────────────────────────
  "A cinematic still with a textbook teal-and-orange grade: warm copper-amber rim light from a sodium lamp sculpting a lone figure in a cool Prussian-blue night warehouse, Kodak Vision3 film stock grain, anamorphic 2.39:1 crop with a horizontal lens flare",
  "A monochrome blue nocturne of an empty fishing village at midnight — cool Prussian blue for the wide sky, dark pewter slate for the still water, near-black silhouettes for the moored clinker boats — a single warm amber window the sole point of relief",
  "A bold triadic still life in pure cadmium crimson, deep cadmium mustard and vivid peacock aquamarine, hand-thrown ceramic vessels arranged on undyed linen cloth",
  "A fashion plate portrait in absolute high-contrast black and white film noir, single hard overhead spot casting deep eye-socket shadow and a sharp blade of jawline highlight, pushed Ilford HP5 grain",
  "Pre-dawn wheat field rendered in the palest warm blush pinks, chalky dusty lemons, and delicate periwinkle blue",
  "A deep forest interior saturated in every tone of emerald, jade and malachite — rain-damp dark bark, deep moss cushions",
  "A warmly faded sepia-tone photograph of a crowded 1904 railway platform, Edwardian crowds in wool coats and top hats, a locomotive exhaling billowing steam",
  "Skate magazine double-page spread circa 1993 in acid-bright colours — skater captured mid-nosegrind on a marble ledge, extreme fisheye barrel distortion, screaming neon yellow and hot pink display typography",
  "A refined Scandinavian interior in a composed palette of dusty mauve, soft sage and unbleached bone — a slubby linen throw, wheel-thrown stoneware mug",
  "An autumn vineyard at peak harvest, rusted iron and burnished copper vine leaves catching low raking light, fine chalk dust hanging in amber shafts of a cold October afternoon sun",

  // ── extras for variety ────────────────────────────────────
  "A perfectly engineered mechanical hummingbird hovering at a flower whose petals are individually lit LED pixels, iridescent chrome feathers and warm organic amber petal-glow in equal balance, 100mm macro studio photography on absolute black",
  "An underground market in a vast cathedral cave system lit by crystal lanterns on every stall, vendors selling impossible things — bottled memories, caged echoes",
  "A single passenger in a wool coat waiting alone on a narrow cliffside train platform above a thousand-foot misty drop, the single-track rail curving sharply into a mountain tunnel, vapour rising from the valley far below",
  "A 1920s Beaux-Arts concert hall completely overtaken by tropical vines and strangler figs, vivid scarlet macaws perched on the gilded balcony rails, a Bösendorfer grand piano sprouting shelf fungi",
  "An ice fisherman's low wooden hut at midnight on a mirror-black frozen lake, a kerosene storm lamp glowing warm orange inside, translucent blue-green ice panels in the floor",
  "A scholar at a cramped library carrel whose small casement window opens directly onto the Orion Nebula at full Hubble resolution, stacks of books beside a cold coffee cup, warm Edison lamp versus cold cosmic pink and blue glow",
  "A Sikorsky-era luxury dirigible mooring at the gilded spire of a snow-dusted Baroque Russian winter palace, ground crew in period overcoats catching mooring lines, fine dry snow falling in blue winter dusk",
  "Istanbul Grand Bazaar spice alley at noon, burlap sacks split to overflow with whole saffron threads, dark crimson sumac",
  "A Victorian cast-iron greenhouse filled entirely with carnivorous plants — towering Nepenthes pitchers hanging from the glazing bars, massed Sarracenia trumpets on the benches, Dionaea traps scattered on the damp moss floor — thick ground-level mist",
  "An antiquarian bookseller in a high-collared waistcoat cataloguing leather-bound folios by the flame of a single tallow taper, bookshelves rising to the ceiling and dissolving into shadow, the nearest spines legible — Hooke",
  "A three-masted tall ship running under every stitch of canvas in a following sea at sunrise, the bow lifting over a green swell and throwing white water to both quarters, gold-edged cumulus building on the warm horizon",
  "An international kite festival over a flooded Bangladeshi delta plain, the sky filled edge to edge with paper box-kites, bamboo-and-tissue dragons in red-gold-green",
  "A desert slot canyon river running crystal-clear turquoise over smooth Navajo sandstone, the walls narrowing above to a slit of ultramarine sky, layered strata of salmon",
  "Beachcombers at extreme low-tide exposure at 4 a.m. on a black Oregon volcanic beach, two figures in waders with hand-swung lanterns searching among exposed rocks, their warm lamplight making amber pools in the pre-dawn blue",
  "A Mississippi River sternwheeler at golden hour churning upriver against the current, the enormous red paddle wheel throwing a sustained arc of white water into the air, spray catching the low western sun in brief rainbows",
  "A snowshoeing party of four striding through a white birch forest two hours after a 60-centimetre overnight snowfall, their tracks in parallel behind, every trunk a white vertical with a faint pink cast in the low winter sun",
  "Aerial photography of the Guerande salt marshes at sunset, the grid of enormous flat pans stretching to the horizon, harvesters scoring perfect parallel lines in the mineral-pink wet surfaces with long wooden rakes",
  "The decaying marquee of a mid-century Art Deco movie palace in a dying Midwestern town, half the remaining bulbs burned out, a rain-warped 1947 film poster in the glass case",
  "A professional sailmaker in a converted stone-walled sail loft, bent over a triple-stitched seam of heavy white Dacron with a sailor's palm and curved needle, a marlinspike hooked on the bench edge",
  "Extreme macro of a bumblebee's compound eye filling two-thirds of the frame, each hexagonal facet perfectly resolved and reflecting within it a tiny image of the open honeycomb it hovers above, the golden comb sharp in the right background",

  // ── more vehicles ──────────────────────────────────────────
  "A 1969 Dodge Charger Daytona in factory Hemi Orange parked broadside on the Bonneville Salt Flats at blue hour, the enormous rear wing casting a long east shadow across the white salt crust, immaculate chrome bumper catching the last sky light",
  "A vintage 1930s mahogany Chris-Craft speedboat at full throttle across a glassy alpine lake at noon, a rooster-tail of diamond spray off the stern, a couple in white period bathing costumes and sun visors aboard",
  "A deep-sea submersible hovering motionless above a black-smoker hydrothermal vent field at 3000 metres, its manipulator arms delicately sampling crimson tube worms, bioluminescent jellyfish drifting through the yellow safety lights",
  "A Dornier Do X twelve-engine flying boat banking in a slow turn over Guanabara Bay in 1932, Sugarloaf Mountain rising below the port wing tip, Rio de Janeiro a white crescent curving along the shoreline",
  "A steam-powered Foden traction engine hauling a painted fairground carousel down a narrow English village high street in autumn rain, polished brass fittings and copper chimney cap gleaming under grey skies, sodden bunting between stone cottages",

  // ── more people / portraits ────────────────────────────────
  "A marine biologist in a black wetsuit holding a live crown-of-thorns starfish at arm's length above a bleached coral reef, sadness and quiet determination in her eyes, shafts of green tropical light filtering from the surface above",
  "An Inuit carver in a worn seal-skin coat shaping a walrus-ivory polar bear figurine with a steel burin, his breath a small cloud in the still Arctic air, cold pale light spilling through a low driftwood doorway across his work-calloused hands",
  "A Flamenco dancer captured mid-zapateado on a sunlit outdoor stage in Seville, her crimson polka-dot bata de cola fanning in a wide arc behind her flying feet, one arm raised in a sharp angular line",
  "A forensic art restorer in white cotton gloves and a binocular magnification headset retouching a crack in a 17th-century oil painting, a fibre-optic lamp raking the surface from one side to reveal brushwork ridges and old varnish layers, pigment and rabbit-skin glue implied",
  "An Andean textile weaver seated at a backstrap loom on a high mountain terrace, brilliant hand-spun yarn in cochineal red and natural indigo blue interlocked in a complex geometric pattern, the snow line of Nevado peaks sharp in the background",

  // ── more landscapes ────────────────────────────────────────
  "The lost city of Petra at dawn, the Treasury's rose-Nabataean facade slowly lit by the first raking slant of desert sun, carved columns emerging from night shadow",
  "A narrow twisting Arizona slot canyon, sinuous walls of Navajo sandstone in strata of salmon, burnt sienna",
  "The Pantanal floodplain at peak wet season, an impossibly flat mirror of still water stretching to every horizon reflecting a towering bone-white cumulus sky, a solitary caiman motionless on a floating mat of violet water hyacinth",
  "Dolomite Tre Cime di Lavaredo at civil twilight, three colossal vertical spires ablaze in deep alpenglow pink and molten gold, a fresh dusting of overnight snow on every ledge and north face",
  "A lonely red-and-white lighthouse on the Maine granite coast during a full nor'easter, a massive Atlantic breaker exploding twenty feet up the rock base in white curtains of foam, wind-driven spray streaming horizontal",

  // ── more fantasy ──────────────────────────────────────────
  "A living city of luminous glass spires rising from the shell of an ancient world-turtle swimming through a starlit cosmic sea, tiny galleons sailing between the towers, silver moonlight refracting through every spire",
  "A faerie blacksmith in a hollow ancient oak forge hammering a sword of compressed starlight on a black iron anvil, tiny sprites working leather bellows at the coals, molten silver light flooding the knothole walls",
  "A sea witch in a kelp-draped tidal cave reading the coming tides in a wide bowl of living indigo ink, five lanternfish on silver chains casting cold aqua bioluminescence, a barnacle-crusted grimoire open to a tide chart",
  "A sleeping giant whose immense body has become a forested hill over three centuries, oaks and beeches rooted in his shoulders, a peaceful village with stone gardens and a white chapel built on the rise of his chest",
  "A blind oracle sitting cross-legged at the exact centre of a marble Doric temple whose roof has long fallen away, four life-size marble serpents coiled around her bare arms, their carved heads raised alert",

  // ── more sci-fi ───────────────────────────────────────────
  "A nuclear-powered terraforming engine the size of a mountain range driving on crawler tracks across the red regolith of Mars, massive atmospheric processors venting superheated steam and nitrogen skyward, a boiling tornado of rust-red dust and compressed gas spiraling in its wake",
  "A generation of humans born aboard a colony ship seeing Earth for the very first time through a curved viewport, faces pressed close to the glass, expressions of wonder and unfamiliarity",
  "A bio-engineered living coral reef city at fifty metres depth in a warm tropical sea, translucent cultured-calcium towers housing thousands of residents, bioluminescent plankton streets pulsing blue",
  "An abandoned international seed vault half-buried in amber methane-rain sediment on Titan, a perpetual orange haze filling the sky, Saturn's ring system faint and vast overhead through the clouds",
  "A solemn diplomatic first-contact tableau: a ring of twelve UN ambassadors in formal dress standing before a vast alien vessel that has soundlessly settled in a snowbound Central Park in January, dry snow drifting from grey sky, the alien's form translated by soft diffuse overcast light into something both strange and dignified",

  // ── more still life ────────────────────────────────────────
  "A chemistry laboratory still life: a rack of eight test tubes filled with iridescent liquids in gradients from topaz to violet, a Bunsen burner with a perfect inner blue cone flame, a well-worn leather lab notebook with pencil calculations",
  "Fly-fishing tackle spread on a weathered cedar dock plank at the river's edge: a hand-tied Adams dry fly still clamped in a brass vise, a worn cork-handled rod with reel, a tippet spool",
  "An architect's drafting board under a raking brass task lamp: a half-finished pencil elevation drawing of a Modernist house, a set of drafting triangles and a flat triangular scale ruler, a lidless Rotring 0.25mm pen drying",
  "A letterpress printing studio still life: hand-set lead type sorts in their compartmented California job case, a gelatin ink roller coated in deep Prussian blue, a proof sheet hanging from a drying line with a single bold line of Caslon set true",
  "A violin maker's bench at end of day: an unfinished spruce top bowed into a go-bar deck with six tension rods, a small iron hide-glue pot still warm, a fan of tiny graduated planes and card scrapers in a leather roll",

  // ── more abstract ─────────────────────────────────────────
  "A cyanotype photogram of an octopus tentacle pressed flat against photosensitive paper and exposed to direct sunlight, the deep Prussian blue background in absolute contrast to the pure white silhouette, every individual sucker precisely rendered as a small circle",
  "Generative art in the style of early 1970s Calcomp plotter drawings: extremely tight concentric contour lines spaced 0.8mm apart describing a human face in a single continuous unbroken thread that never crosses itself, white ink on black card, the face emerging from purely mathematical topology",
  "A Murano glass maestro's interpretation of the aurora borealis realised as a single blown piece: interlocking swirling ribbons of cobalt, emerald, pale gold and violet suspended inside a flawless clear glass sphere thirty centimetres across",
  "A double-exposure composite of a Bengal tiger and a dense tropical bamboo rainforest, the tiger's dark stripes seamlessly becoming the vertical spaces between bamboo culms, the amber eye the only pure colour among the deep greens",
  "A tapestry of interconnected city maps woven in a medieval Flemish millefleurs style — street grids becoming the warp threads, bridges as woven overshots, landmarks as gold-thread pictograms — Amsterdam",

  // ── more atmospheric ───────────────────────────────────────
  "A mature tropical cyclone seen from the ISS at 400 km altitude, the perfectly symmetrical eye centred in the frame, the spiral cloud bands stretching 1500 km in every direction across the deep cobalt Pacific",
  "A derecho squall line 100 miles long rolling southeast across the Kansas Great Plains at dusk, the enormous backlit arcus shelf cloud glowing amber and ochre at the base, embedded lightning strobing white deep within the storm mass",
  "A sea fog bank advancing on the Northern California redwood coast at the pace of the incoming tide, only the crown of the tallest trees projecting above the white vapour, a lighthouse beam cutting a clean arc through the fog every four seconds",

  // ── more people in context ─────────────────────────────────
  "A solo long-distance cyclist cresting a high Pyrenean mountain pass at dawn, standing on the pedals in the last exhausted effort, panniers fore and aft",
  "A traditional Japanese swordsmith forging a glowing tamahagane billet with his apprentice in a dark earthen-floored forge, both wearing white cotton hadagi and hachimaki headbands, the billet radiating deep blood-red light",
  "A retired schoolteacher arranging pressed wildflowers in a leather-bound botanical album at a garden table in full summer, a magnifying glass to check placement, a glass of iced tea catching the afternoon light",
  "A Makah canoe carver deep in an ancient cedar grove, one hand pressed to the bark of a chosen log, eyes closed",
  "Two marine biologists on a night dive in a phosphorescent bay, their slow fin-kicks stirring constellations of cold blue bioluminescent sparks that trail behind them in the black water, a coral reef faintly lit by their torches below",

  // ── more conceptual ───────────────────────────────────────
  "An astronaut in a full white Extravehicular Mobility Unit relaxing in a nylon hammock strung between two tall palm trees on a deserted tropical island beach, helmet resting in the sand beside a paperback novel, a set of clear footprints leading down to the tideline",
  "A high-speed Swiss ICE train crossing a tall stone viaduct above a steep Slovenian river gorge at peak autumn colour, the train itself a white motion blur, the mirror-still turquoise Soča river below in absolute stillness",
  "A master glassblower at a roaring glory-hole furnace at midnight, a massive glowing orange gather of molten soda-lime on the end of a five-foot blowpipe, his assistant standing ready with diamond-point jacks",
];



